name: CodeGen Security-Check
on:
  #schedule:
  #  - cron: '0 18 * * *' # Daily at 18:00 UTC
  pull_request:
    branches: [ master ]

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo sed /etc/apt/sources.list -e "s/^# deb-src/deb-src/g" -i
          sudo apt-get update
          sudo apt-get install ruby2.5
          sudo apt-get build-dep ruby2.5

      - name: Checkout simplify-framework/simplify-codegen
        run: |
          git clone --depth=1 https://github.com/simplify-framework/codegen .

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/linux64 --post-data "token=$TOKEN&project=simplify-codegen" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Fetch CodeGen dependancies
        run: npm install

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int --fs-capture-search ./ npm install

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf simplify-codegen.tgz cov-int
          curl \
            --form project=simplify-codegen \
            --form token=$TOKEN \
            --form email=codegen@simplify-framwork.org \
            --form file=@simplify-codegen.tgz \
            --form version=latest \
            --form description="Simplify Codegen Security Scan" \
            https://scan.coverity.com/builds?project=simplify-codegen
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}