# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm link
    - run: npm link simplify-codegen
    - run: simplify-codegen petsample -p ${{ secrets.PROJECT_ID }}
    - run: sed -i '/^x-deployment-profile:/d' openapi.yaml
    - run: simplify-codegen generate -i openapi.yaml -p ${{ secrets.PROJECT_ID }} -a ${{ secrets.AWS_ACCOUNT_ID }} -o $PWD/ci-test
    - run: sed -i '/^ENV_functionForPets_DEPLOYMENT_STAGE/s/=.*$/=stable/' $PWD/ci-test/.env
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubCISession
        role-duration-seconds: 1200
    - run: cd $PWD/ci-test && ls
    - run: cd $PWD/ci-test && npm install
    - run: cd $PWD/ci-test && npm run stack-deploy
    - run: cd $PWD/ci-test && npm run push-code
    - run: cd $PWD/ci-test && npm run test
    - run: cd $PWD/ci-test && sed -i '/^ENV_functionForPets_DEPLOYMENT_STAGE/s/=.*$/=enforce/' .env
    - run: cd $PWD/ci-test && sed -i '/^ENV_functionForPets_ENFORCEMENT_PACKAGE/s/=.*$/=function-for-pets-v10/' .env
    - run: cd $PWD/ci-test && npm run push-code
    - run: cd $PWD/ci-test && npm run test
    #- run: cd $PWD/ci-test && sed -i '/^ENV_functionForPets_DEPLOYMENT_STAGE/s/=.*$/=canary/' .env
    #- run: cd $PWD/ci-test && npm run push-update
    #- run: cd $PWD/ci-test && npm run test-apis
    - run: cd $PWD/ci-test && npm run stack-destroy
